export const createPageStyles = {
    page: { color: '#0f172a' },
    header: {
        display: 'flex',
        justifyContent: 'space-between',
        gap: '20px',
        alignItems: 'flex-end',
        marginBottom: '24px',
        flexWrap: 'wrap',
    },
    kicker: {
        margin: 0,
        color: '#2563eb',
        fontWeight: 700,
        letterSpacing: '0.08em',
        textTransform: 'uppercase',
        fontSize: '12px',
    },
    title: { margin: '8px 0', fontSize: '32px', fontWeight: 800 },
    subtitle: { margin: 0, color: '#475569', maxWidth: '720px', lineHeight: 1.5 },
    actions: { display: 'flex', gap: '12px', flexWrap: 'wrap' },
    secondaryLink: {
        textDecoration: 'none',
        border: '1px solid #cbd5e1',
        color: '#0f172a',
        background: '#ffffff',
        padding: '10px 14px',
        borderRadius: '10px',
        fontWeight: 700,
    },
    form: {
        background: '#ffffff',
        border: '1px solid #e2e8f0',
        borderRadius: '16px',
        padding: '24px',
        display: 'grid',
        gap: '20px',
        maxWidth: '980px',
        boxShadow: '0 1px 2px rgba(15, 23, 42, 0.04)',
    },
    grid: {
        display: 'grid',
        gridTemplateColumns: 'repeat(auto-fit, minmax(240px, 1fr))',
        gap: '16px',
    },
    label: { display: 'grid', gap: '8px', color: '#334155', fontWeight: 700 },
    input: {
        width: '100%',
        boxSizing: 'border-box',
        border: '1px solid #cbd5e1',
        borderRadius: '8px',
        padding: '11px 12px',
        color: '#0f172a',
        background: '#ffffff',
        outlineColor: '#0891b2',
    },
    textarea: {
        width: '100%',
        boxSizing: 'border-box',
        border: '1px solid #cbd5e1',
        borderRadius: '10px',
        padding: '11px 12px',
        color: '#0f172a',
        background: '#ffffff',
        minHeight: '110px',
        resize: 'vertical',
    },
    section: {
        border: '1px solid #dbeafe',
        borderRadius: '14px',
        padding: '16px',
        background: '#f8fbff',
    },
    sectionTitle: { margin: '0 0 12px', fontSize: '20px', color: '#0f172a' },
    row: {
        display: 'grid',
        gridTemplateColumns: 'repeat(auto-fit, minmax(180px, 1fr))',
        gap: '12px',
        marginBottom: '12px',
    },
    primaryButton: {
        border: 'none',
        background: '#2563eb',
        color: '#ffffff',
        padding: '12px 16px',
        borderRadius: '10px',
        fontWeight: 800,
        cursor: 'pointer',
    },
    secondaryButton: {
        border: '1px solid #cbd5e1',
        color: '#0f172a',
        background: '#ffffff',
        padding: '10px 14px',
        borderRadius: '10px',
        fontWeight: 700,
        cursor: 'pointer',
    },
    notice: {
        background: '#ffffff',
        border: '1px solid #e2e8f0',
        borderRadius: '14px',
        padding: '18px',
        color: '#475569',
        marginBottom: '16px',
    },
    success: {
        background: '#ecfdf5',
        border: '1px solid #bbf7d0',
        borderRadius: '14px',
        padding: '18px',
        color: '#166534',
        marginBottom: '16px',
    },
    error: {
        background: '#fef2f2',
        border: '1px solid #fecaca',
        borderRadius: '14px',
        padding: '18px',
        color: '#991b1b',
        marginBottom: '16px',
    },
};
